### ISSUE TITLE
quering an invalid inventoryID with paging=true causes a redirect loop

### ISSUE THREAD

**Issue by YoctoByte** [delving/hub3#111]
Querying `/api/tree/<spec>/<invalid inventoryID>?paging=true` causes a HTTP 303 response which redirects to the same url.

Proposed fix:
Add `&& searchRequest.Tree.Page[0] != 1` to [hub3/hub3/server/http/handlers/search.go line 419](https://github.com/delving/hub3/blob/52e22f40f3e3aa24f5f954902383090e8c1854b5/hub3/server/http/handlers/search.go#L419)
This way the redirect does not happen if the page already is page 1.

**Comment by kiivihal** [comment]
I think the workflow is dependent on a query being present in the query params. If we search for something on a specific inventoryID and we get 0 results it should show the first page. 

If we get zero results because the inventoryID is invalid then we should not have a 'q' in the query params. If we do, we terminate with a 404. 

A solution could be:

```golang
		if paging.HitsTotalCount == 0 && searchRequest.Tree.IsSearch && searchRequest.Tree.IsPaging {
			// if there is no query in the params then this is already a redirect
			if !r.URL.Query().Has("q") {
				http.Error(w, fmt.Sprintf("inventoryID '%s' not found", searchRequest.Tree.UnitID), http.StatusNotFound)
				return
			}
			newPath := fmt.Sprintf("%s?paging=true&page=1", r.URL.Path)
			http.Redirect(w, r, newPath, http.StatusSeeOther)
			return
		}

```
